# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.29

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/linuxbrew/.linuxbrew/Cellar/cmake/3.29.2/bin/cmake

# The command to remove a file.
RM = /home/linuxbrew/.linuxbrew/Cellar/cmake/3.29.2/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /workspace/Labyrinth_Cpp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /workspace/Labyrinth_Cpp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/home/linuxbrew/.linuxbrew/Cellar/cmake/3.29.2/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/home/linuxbrew/.linuxbrew/Cellar/cmake/3.29.2/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /workspace/Labyrinth_Cpp/CMakeFiles /workspace/Labyrinth_Cpp//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /workspace/Labyrinth_Cpp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Labyrinth

# Build rule for target.
Labyrinth: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Labyrinth
.PHONY : Labyrinth

# fast build rule for target.
Labyrinth/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Labyrinth.dir/build.make CMakeFiles/Labyrinth.dir/build
.PHONY : Labyrinth/fast

AbilityClasses.o: AbilityClasses.cpp.o
.PHONY : AbilityClasses.o

# target to build an object file
AbilityClasses.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Labyrinth.dir/build.make CMakeFiles/Labyrinth.dir/AbilityClasses.cpp.o
.PHONY : AbilityClasses.cpp.o

AbilityClasses.i: AbilityClasses.cpp.i
.PHONY : AbilityClasses.i

# target to preprocess a source file
AbilityClasses.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Labyrinth.dir/build.make CMakeFiles/Labyrinth.dir/AbilityClasses.cpp.i
.PHONY : AbilityClasses.cpp.i

AbilityClasses.s: AbilityClasses.cpp.s
.PHONY : AbilityClasses.s

# target to generate assembly for a file
AbilityClasses.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Labyrinth.dir/build.make CMakeFiles/Labyrinth.dir/AbilityClasses.cpp.s
.PHONY : AbilityClasses.cpp.s

Enchantments.o: Enchantments.cpp.o
.PHONY : Enchantments.o

# target to build an object file
Enchantments.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Labyrinth.dir/build.make CMakeFiles/Labyrinth.dir/Enchantments.cpp.o
.PHONY : Enchantments.cpp.o

Enchantments.i: Enchantments.cpp.i
.PHONY : Enchantments.i

# target to preprocess a source file
Enchantments.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Labyrinth.dir/build.make CMakeFiles/Labyrinth.dir/Enchantments.cpp.i
.PHONY : Enchantments.cpp.i

Enchantments.s: Enchantments.cpp.s
.PHONY : Enchantments.s

# target to generate assembly for a file
Enchantments.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Labyrinth.dir/build.make CMakeFiles/Labyrinth.dir/Enchantments.cpp.s
.PHONY : Enchantments.cpp.s

Enemies.o: Enemies.cpp.o
.PHONY : Enemies.o

# target to build an object file
Enemies.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Labyrinth.dir/build.make CMakeFiles/Labyrinth.dir/Enemies.cpp.o
.PHONY : Enemies.cpp.o

Enemies.i: Enemies.cpp.i
.PHONY : Enemies.i

# target to preprocess a source file
Enemies.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Labyrinth.dir/build.make CMakeFiles/Labyrinth.dir/Enemies.cpp.i
.PHONY : Enemies.cpp.i

Enemies.s: Enemies.cpp.s
.PHONY : Enemies.s

# target to generate assembly for a file
Enemies.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Labyrinth.dir/build.make CMakeFiles/Labyrinth.dir/Enemies.cpp.s
.PHONY : Enemies.cpp.s

Loot/Items.o: Loot/Items.cpp.o
.PHONY : Loot/Items.o

# target to build an object file
Loot/Items.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Labyrinth.dir/build.make CMakeFiles/Labyrinth.dir/Loot/Items.cpp.o
.PHONY : Loot/Items.cpp.o

Loot/Items.i: Loot/Items.cpp.i
.PHONY : Loot/Items.i

# target to preprocess a source file
Loot/Items.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Labyrinth.dir/build.make CMakeFiles/Labyrinth.dir/Loot/Items.cpp.i
.PHONY : Loot/Items.cpp.i

Loot/Items.s: Loot/Items.cpp.s
.PHONY : Loot/Items.s

# target to generate assembly for a file
Loot/Items.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Labyrinth.dir/build.make CMakeFiles/Labyrinth.dir/Loot/Items.cpp.s
.PHONY : Loot/Items.cpp.s

Loot/LootTables/Shop.o: Loot/LootTables/Shop.cpp.o
.PHONY : Loot/LootTables/Shop.o

# target to build an object file
Loot/LootTables/Shop.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Labyrinth.dir/build.make CMakeFiles/Labyrinth.dir/Loot/LootTables/Shop.cpp.o
.PHONY : Loot/LootTables/Shop.cpp.o

Loot/LootTables/Shop.i: Loot/LootTables/Shop.cpp.i
.PHONY : Loot/LootTables/Shop.i

# target to preprocess a source file
Loot/LootTables/Shop.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Labyrinth.dir/build.make CMakeFiles/Labyrinth.dir/Loot/LootTables/Shop.cpp.i
.PHONY : Loot/LootTables/Shop.cpp.i

Loot/LootTables/Shop.s: Loot/LootTables/Shop.cpp.s
.PHONY : Loot/LootTables/Shop.s

# target to generate assembly for a file
Loot/LootTables/Shop.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Labyrinth.dir/build.make CMakeFiles/Labyrinth.dir/Loot/LootTables/Shop.cpp.s
.PHONY : Loot/LootTables/Shop.cpp.s

Loot/LootTables/SkeletonTheif_Enemy.o: Loot/LootTables/SkeletonTheif_Enemy.cpp.o
.PHONY : Loot/LootTables/SkeletonTheif_Enemy.o

# target to build an object file
Loot/LootTables/SkeletonTheif_Enemy.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Labyrinth.dir/build.make CMakeFiles/Labyrinth.dir/Loot/LootTables/SkeletonTheif_Enemy.cpp.o
.PHONY : Loot/LootTables/SkeletonTheif_Enemy.cpp.o

Loot/LootTables/SkeletonTheif_Enemy.i: Loot/LootTables/SkeletonTheif_Enemy.cpp.i
.PHONY : Loot/LootTables/SkeletonTheif_Enemy.i

# target to preprocess a source file
Loot/LootTables/SkeletonTheif_Enemy.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Labyrinth.dir/build.make CMakeFiles/Labyrinth.dir/Loot/LootTables/SkeletonTheif_Enemy.cpp.i
.PHONY : Loot/LootTables/SkeletonTheif_Enemy.cpp.i

Loot/LootTables/SkeletonTheif_Enemy.s: Loot/LootTables/SkeletonTheif_Enemy.cpp.s
.PHONY : Loot/LootTables/SkeletonTheif_Enemy.s

# target to generate assembly for a file
Loot/LootTables/SkeletonTheif_Enemy.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Labyrinth.dir/build.make CMakeFiles/Labyrinth.dir/Loot/LootTables/SkeletonTheif_Enemy.cpp.s
.PHONY : Loot/LootTables/SkeletonTheif_Enemy.cpp.s

Loot/LootTables/Skeleton_Enemy.o: Loot/LootTables/Skeleton_Enemy.cpp.o
.PHONY : Loot/LootTables/Skeleton_Enemy.o

# target to build an object file
Loot/LootTables/Skeleton_Enemy.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Labyrinth.dir/build.make CMakeFiles/Labyrinth.dir/Loot/LootTables/Skeleton_Enemy.cpp.o
.PHONY : Loot/LootTables/Skeleton_Enemy.cpp.o

Loot/LootTables/Skeleton_Enemy.i: Loot/LootTables/Skeleton_Enemy.cpp.i
.PHONY : Loot/LootTables/Skeleton_Enemy.i

# target to preprocess a source file
Loot/LootTables/Skeleton_Enemy.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Labyrinth.dir/build.make CMakeFiles/Labyrinth.dir/Loot/LootTables/Skeleton_Enemy.cpp.i
.PHONY : Loot/LootTables/Skeleton_Enemy.cpp.i

Loot/LootTables/Skeleton_Enemy.s: Loot/LootTables/Skeleton_Enemy.cpp.s
.PHONY : Loot/LootTables/Skeleton_Enemy.s

# target to generate assembly for a file
Loot/LootTables/Skeleton_Enemy.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Labyrinth.dir/build.make CMakeFiles/Labyrinth.dir/Loot/LootTables/Skeleton_Enemy.cpp.s
.PHONY : Loot/LootTables/Skeleton_Enemy.cpp.s

Loot/LootTables/Unwilling_Enemy.o: Loot/LootTables/Unwilling_Enemy.cpp.o
.PHONY : Loot/LootTables/Unwilling_Enemy.o

# target to build an object file
Loot/LootTables/Unwilling_Enemy.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Labyrinth.dir/build.make CMakeFiles/Labyrinth.dir/Loot/LootTables/Unwilling_Enemy.cpp.o
.PHONY : Loot/LootTables/Unwilling_Enemy.cpp.o

Loot/LootTables/Unwilling_Enemy.i: Loot/LootTables/Unwilling_Enemy.cpp.i
.PHONY : Loot/LootTables/Unwilling_Enemy.i

# target to preprocess a source file
Loot/LootTables/Unwilling_Enemy.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Labyrinth.dir/build.make CMakeFiles/Labyrinth.dir/Loot/LootTables/Unwilling_Enemy.cpp.i
.PHONY : Loot/LootTables/Unwilling_Enemy.cpp.i

Loot/LootTables/Unwilling_Enemy.s: Loot/LootTables/Unwilling_Enemy.cpp.s
.PHONY : Loot/LootTables/Unwilling_Enemy.s

# target to generate assembly for a file
Loot/LootTables/Unwilling_Enemy.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Labyrinth.dir/build.make CMakeFiles/Labyrinth.dir/Loot/LootTables/Unwilling_Enemy.cpp.s
.PHONY : Loot/LootTables/Unwilling_Enemy.cpp.s

Loot/LootTables/Wood_Chest.o: Loot/LootTables/Wood_Chest.cpp.o
.PHONY : Loot/LootTables/Wood_Chest.o

# target to build an object file
Loot/LootTables/Wood_Chest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Labyrinth.dir/build.make CMakeFiles/Labyrinth.dir/Loot/LootTables/Wood_Chest.cpp.o
.PHONY : Loot/LootTables/Wood_Chest.cpp.o

Loot/LootTables/Wood_Chest.i: Loot/LootTables/Wood_Chest.cpp.i
.PHONY : Loot/LootTables/Wood_Chest.i

# target to preprocess a source file
Loot/LootTables/Wood_Chest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Labyrinth.dir/build.make CMakeFiles/Labyrinth.dir/Loot/LootTables/Wood_Chest.cpp.i
.PHONY : Loot/LootTables/Wood_Chest.cpp.i

Loot/LootTables/Wood_Chest.s: Loot/LootTables/Wood_Chest.cpp.s
.PHONY : Loot/LootTables/Wood_Chest.s

# target to generate assembly for a file
Loot/LootTables/Wood_Chest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Labyrinth.dir/build.make CMakeFiles/Labyrinth.dir/Loot/LootTables/Wood_Chest.cpp.s
.PHONY : Loot/LootTables/Wood_Chest.cpp.s

Loot/TableReader.o: Loot/TableReader.cpp.o
.PHONY : Loot/TableReader.o

# target to build an object file
Loot/TableReader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Labyrinth.dir/build.make CMakeFiles/Labyrinth.dir/Loot/TableReader.cpp.o
.PHONY : Loot/TableReader.cpp.o

Loot/TableReader.i: Loot/TableReader.cpp.i
.PHONY : Loot/TableReader.i

# target to preprocess a source file
Loot/TableReader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Labyrinth.dir/build.make CMakeFiles/Labyrinth.dir/Loot/TableReader.cpp.i
.PHONY : Loot/TableReader.cpp.i

Loot/TableReader.s: Loot/TableReader.cpp.s
.PHONY : Loot/TableReader.s

# target to generate assembly for a file
Loot/TableReader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Labyrinth.dir/build.make CMakeFiles/Labyrinth.dir/Loot/TableReader.cpp.s
.PHONY : Loot/TableReader.cpp.s

Player.o: Player.cpp.o
.PHONY : Player.o

# target to build an object file
Player.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Labyrinth.dir/build.make CMakeFiles/Labyrinth.dir/Player.cpp.o
.PHONY : Player.cpp.o

Player.i: Player.cpp.i
.PHONY : Player.i

# target to preprocess a source file
Player.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Labyrinth.dir/build.make CMakeFiles/Labyrinth.dir/Player.cpp.i
.PHONY : Player.cpp.i

Player.s: Player.cpp.s
.PHONY : Player.s

# target to generate assembly for a file
Player.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Labyrinth.dir/build.make CMakeFiles/Labyrinth.dir/Player.cpp.s
.PHONY : Player.cpp.s

Random_Function.o: Random_Function.cpp.o
.PHONY : Random_Function.o

# target to build an object file
Random_Function.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Labyrinth.dir/build.make CMakeFiles/Labyrinth.dir/Random_Function.cpp.o
.PHONY : Random_Function.cpp.o

Random_Function.i: Random_Function.cpp.i
.PHONY : Random_Function.i

# target to preprocess a source file
Random_Function.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Labyrinth.dir/build.make CMakeFiles/Labyrinth.dir/Random_Function.cpp.i
.PHONY : Random_Function.cpp.i

Random_Function.s: Random_Function.cpp.s
.PHONY : Random_Function.s

# target to generate assembly for a file
Random_Function.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Labyrinth.dir/build.make CMakeFiles/Labyrinth.dir/Random_Function.cpp.s
.PHONY : Random_Function.cpp.s

UseEvents.o: UseEvents.cpp.o
.PHONY : UseEvents.o

# target to build an object file
UseEvents.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Labyrinth.dir/build.make CMakeFiles/Labyrinth.dir/UseEvents.cpp.o
.PHONY : UseEvents.cpp.o

UseEvents.i: UseEvents.cpp.i
.PHONY : UseEvents.i

# target to preprocess a source file
UseEvents.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Labyrinth.dir/build.make CMakeFiles/Labyrinth.dir/UseEvents.cpp.i
.PHONY : UseEvents.cpp.i

UseEvents.s: UseEvents.cpp.s
.PHONY : UseEvents.s

# target to generate assembly for a file
UseEvents.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Labyrinth.dir/build.make CMakeFiles/Labyrinth.dir/UseEvents.cpp.s
.PHONY : UseEvents.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Labyrinth.dir/build.make CMakeFiles/Labyrinth.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Labyrinth.dir/build.make CMakeFiles/Labyrinth.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Labyrinth.dir/build.make CMakeFiles/Labyrinth.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Labyrinth"
	@echo "... AbilityClasses.o"
	@echo "... AbilityClasses.i"
	@echo "... AbilityClasses.s"
	@echo "... Enchantments.o"
	@echo "... Enchantments.i"
	@echo "... Enchantments.s"
	@echo "... Enemies.o"
	@echo "... Enemies.i"
	@echo "... Enemies.s"
	@echo "... Loot/Items.o"
	@echo "... Loot/Items.i"
	@echo "... Loot/Items.s"
	@echo "... Loot/LootTables/Shop.o"
	@echo "... Loot/LootTables/Shop.i"
	@echo "... Loot/LootTables/Shop.s"
	@echo "... Loot/LootTables/SkeletonTheif_Enemy.o"
	@echo "... Loot/LootTables/SkeletonTheif_Enemy.i"
	@echo "... Loot/LootTables/SkeletonTheif_Enemy.s"
	@echo "... Loot/LootTables/Skeleton_Enemy.o"
	@echo "... Loot/LootTables/Skeleton_Enemy.i"
	@echo "... Loot/LootTables/Skeleton_Enemy.s"
	@echo "... Loot/LootTables/Unwilling_Enemy.o"
	@echo "... Loot/LootTables/Unwilling_Enemy.i"
	@echo "... Loot/LootTables/Unwilling_Enemy.s"
	@echo "... Loot/LootTables/Wood_Chest.o"
	@echo "... Loot/LootTables/Wood_Chest.i"
	@echo "... Loot/LootTables/Wood_Chest.s"
	@echo "... Loot/TableReader.o"
	@echo "... Loot/TableReader.i"
	@echo "... Loot/TableReader.s"
	@echo "... Player.o"
	@echo "... Player.i"
	@echo "... Player.s"
	@echo "... Random_Function.o"
	@echo "... Random_Function.i"
	@echo "... Random_Function.s"
	@echo "... UseEvents.o"
	@echo "... UseEvents.i"
	@echo "... UseEvents.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

